### ISSUE TITLE
Download Report crashes browser

### ISSUE THREAD

**Issue by muralithiyagarajan** [bodastage/bts-ce#68] opened 2019-04-28 11:53 UTC
Download Report crashes browser

Failed to load resource: net::ERR_INSUFFICIENT_RESOURCES

**Comment by erssebaggala** [comment] 2019-05-27 10:00
This was caused by the use of setInterval in the UI to check if the download is ready. 

This was fixed in  PR #69

**Closed by erssebaggala** 2019-05-27 10:00 UTC
